### ISSUE TITLE
Misplaced controller

### ISSUE THREAD

**Issue by akritikts** [bertrandmartel/youtubetv#2]
The playback controller comes up in the middle of the screen.

**Comment by bertrandmartel** [comment]
The same as Youtube app as expected, why not ?

**Comment by akritikts** [comment]
The playback controller should be at the bottom of the screen.

**Comment by bertrandmartel** [comment]
Do you mean the playback controls ( [`PlaybackOverlayFragment`](https://developer.android.com/reference/android/support/v17/leanback/app/PlaybackOverlayFragment.html) ) ? 

Youtube app 
![device-2017-05-02-200617](https://cloud.githubusercontent.com/assets/5183022/25632371/aced8ec8-2f73-11e7-91df-ba75d8e8cfd0.png)

Library
![device-2017-05-02-200819](https://cloud.githubusercontent.com/assets/5183022/25632399/c224a27c-2f73-11e7-8c80-e28486f65273.png)


Note that using [`PlaybackOverlayFragment`](https://developer.android.com/reference/android/support/v17/leanback/app/PlaybackOverlayFragment.html) is the recommended way to display playback controls on Android TV

**Comment by akritikts** [comment]
Yeah, I was talking about this. 
If that is the recommended way then it's fine.

**Comment by bertrandmartel** [comment]
But, from [Google style guide for Android TV,](https://www.google.com/design/spec-tv/tv-apps/consumption-view.html#) it does not specify that it has to be in the center of the screen, you are right about that for instance 

![app_structure_consumption](https://cloud.githubusercontent.com/assets/5183022/25633013/f06ff8a0-2f75-11e7-88fb-83d4db631584.jpg)

Also `YoutubeTvFragment` is based on the example of leanback from Google, you can create your own playback fragment if you want to (with additional controls and content like in Youtube app)

I will check if I can parameter the playback controls position as above

**Comment by akritikts** [comment]
Ok
